name: build default image

on: [create]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y build-essential make cmake libpcre3 libpcre3-dev bc bison flex python3-numpy mtd-utils zlib1g-dev debootstrap libdata-hexdumper-perl libncurses5-dev zip qemu-user-static curl repo git liblz4-tool apt-cacher-ng libssl-dev checkpolicy autoconf 
          curl -fO http://archive.sunrisepi.tech/toolchain/gcc-ubuntu-9.3.0-2020.03-x86_64-aarch64-linux-gnu.tar.xz
          sudo tar -xvf gcc-ubuntu-9.3.0-2020.03-x86_64-aarch64-linux-gnu.tar.xz -C /opt
      - name: Set environment variables for cross-compiling toolchains
        run: |
          export CROSS_COMPILE=/opt/gcc-ubuntu-9.3.0-2020.03-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-
          export LD_LIBRARY_PATH=/opt/gcc-ubuntu-9.3.0-2020.03-x86_64-aarch64-linux-gnu/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
          export PATH=$PATH:/opt/gcc-ubuntu-9.3.0-2020.03-x86_64-aarch64-linux-gnu/bin/
          export ARCH=arm64
      - name: Package system image and rootfs
        run: |
          # git submodule update --init --recursive
          # cd rdk-gen
          sudo ./pack_image.sh
          mkdir out
          sudo tar zcvf out/ubuntu-preinstalled-desktop-arm64.tar.xz deploy/ubuntu-preinstalled-desktop-arm64.img
          sudo tar zcvf out/rootfs.tar.xz deploy/rootfs
          sudo chmod 777 out/*
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: rdk-gen-release
          path: rdk-gen/out 
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "rdk-gen/out/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
